### PR TITLE
Accept UIAppearance

### PR DESCRIPTION
**Pull request by diogomaximo**
Added capacity to customize layout using UIAppearance
Now you have one alternative to customize TSMessageView, you can use UIAppearance.
These are the properties 
```objective-c
[TSMessageView appearance] setTitleFont:[UIFont boldSystemFontOfSize:6]];
[[TSMessageView appearance] setTitleTextColor:[UIColor redColor]];
[[TSMessageView appearance] setContentFont:[UIFont boldSystemFontOfSize:10]];
[[TSMessageView appearance]setContentTextColor:[UIColor greenColor]];
[[TSMessageView appearance]setErrorIcon:[UIImage imageNamed:@"NotificationButtonBackground"]];
[[TSMessageView appearance]setSuccessIcon:[UIImage imageNamed:@"NotificationButtonBackground"]];
[[TSMessageView appearance]setMessageIcon:[UIImage imageNamed:@"NotificationButtonBackground"]];
[[TSMessageView appearance]setWarningIcon:[UIImage imageNamed:@"NotificationButtonBackground"]];
```

### CODE REVIEW

**Comment by shams-ahmed** [comment]
@KrauseFx whats your thoughts about this PR? i think it a really good approach to using custom design...

**Comment by rodrigocotton** [comment]
+1 @KrauseFx

**Comment by shams-ahmed** [comment]
Any updates on this?

**Comment by KrauseFx** [comment]
Looks great, thanks for the pull request :+1: 

Could you just fix the merge conflicts:

> We can’t automatically merge this pull request.

Thanks!

**Comment by shams-ahmed** [comment]
Thanks!

**Comment by diogomaximo** [comment]
@KrauseFx Merged with 'master'.

**Comment by KrauseFx** [comment]
Thanks @diogomaximo for working on this! :+1:

**Comment by KrauseFx** [comment]
And sorry it took so long :disappointed:

**Pull request merged**
