### PR TITLE
Updated the library to use HexColors 2.3.0

### PR DESCRIPTION
**Pull request by mRs-**
With this update we can use the current Version with HexColors 2.3.0 :)

### CODE REVIEW

**Comment by xavierjurado** [comment]
:+1:

**Comment by xavierjurado** [comment]
We should also specify the minimum required version of HexColors inside the podspec file to prevent similar issues in the future @mRs- 

```yaml
s.dependency 'HexColors', '~> 2.3.0'
```

**Comment by KrauseFx** [comment]
@mRs- Shouldn't that be a major version bump as it breaks compatibility?

**Comment by mRs-** [comment]
I think the main problem was in the Podfile of TSMessages, because of the missing version number `s.dependency 'HexColors', '~> 2.3.0'`

I will hand in a merge request today with the suggestion from @xavierjurado

**Comment by KrauseFx** [comment]
Thanks :+1:

**Pull request merged**
